name: Increment Semantic Version
description: Bump a given semantic version by a release type ( major | minor | patch )
author: Christian Dräger
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  current-version:
    description: 'The current semantic version you want to increment'
    required: true
  release-type:
    description: 'The release type. Possible options are [ major | feature | fix | refactor | docs ]'
    required: true
outputs:
  new-version:
    description: 'The new incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.current-version }}
    - ${{ inputs.release-type }}
